apiVersion: v1
kind: Pod
metadata:
  name: nginx-req
  labels:
    key: app
    value: blue
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - medium
            - small
