apiVersion: v1
kind: Pod
metadata:
  name: nginx-pref
  labels:
    key: app
    value: blue
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: size
            operator: In
            values:
            - medium
      - weight: 50
        preference:
          matchExpressions:
          - key: size
            operator: In
            values:
            - small
